# Generated by Django 4.1 on 2022-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_group_name', models.TextField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='description of the group')),
            ],
        ),
    ]
