# Generated by Django 4.1 on 2022-10-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinchatgroup',
            old_name='User',
            new_name='user',
        ),
    ]
