# Generated by Django 4.1 on 2022-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0002_rename_user_userinchatgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='chat_group_name',
            field=models.TextField(max_length=100),
        ),
    ]
