# Generated by Django 4.1 on 2022-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0003_alter_chatgroup_chat_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/'),
        ),
    ]
