# Generated by Django 4.1 on 2022-10-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0004_alter_chatgroup_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinchatgroup',
            old_name='user',
            new_name='profile',
        ),
    ]
