# Generated by Django 4.1 on 2022-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_group', '0005_rename_user_userinchatgroup_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinchatgroup',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
